import {Request} from '@prisma/client';

export const presentRequest = (request: Request, distanceMeters?: number) => ({
  id: request.id,
  requesterId: request.requesterId,
  creatorId: request.creatorId,
  type: request.type,
  scheduledAt: request.scheduledAt?.toISOString() ?? null,
  location: {
    latitude: request.latitude,
    longitude: request.longitude,
    formattedAddress: request.formattedAddress,
    category: request.locationCategory,
    radiusMeters: request.radiusMeters,
  },
  description: request.description,
  durationMinutes: request.durationMinutes,
  rewardAmount: Number(request.rewardAmount),
  category: request.category,
  instructions: request.instructions,
  status: request.status,
  highValueReviewRequired: request.highValueReviewRequired,
  reshootUsed: request.reshootUsed,
  reshootCount: request.reshootCount,
  requesterDeclarationAt: request.requesterDeclarationAt.toISOString(),
  acceptedAt: request.acceptedAt?.toISOString() ?? null,
  acceptanceTimerExpiresAt: request.acceptanceTimerExpiresAt?.toISOString() ?? null,
  recordingStartedAt: request.recordingStartedAt?.toISOString() ?? null,
  uploadedAt: request.uploadedAt?.toISOString() ?? null,
  moderatorDecisionAt: request.moderatorDecisionAt?.toISOString() ?? null,
  moderatorRejectionReason: request.moderatorRejectionReason,
  requesterDecisionAt: request.requesterDecisionAt?.toISOString() ?? null,
  requesterReviewRemarks: request.requesterReviewRemarks,
  requesterRejectionReason: request.requesterRejectionReason,
  reshootReason: request.reshootReason,
  cancelledAt: request.cancelledAt?.toISOString() ?? null,
  cancellationReason: request.cancellationReason,
  expiresAt: request.expiresAt.toISOString(),
  createdAt: request.createdAt.toISOString(),
  updatedAt: request.updatedAt.toISOString(),
  ...(distanceMeters !== undefined ? {distanceMeters: Math.round(distanceMeters)} : {}),
});
